/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmergencyContactsRouteImport } from './routes/emergency-contacts'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicalProfileRouteImport } from './routes/medical-profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SosRouteImport } from './routes/sos'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardChatbotRouteImport } from './routes/dashboard.chatbot'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard.doctor'
import { Route as DashboardDriverRouteImport } from './routes/dashboard.driver'
import { Route as DashboardHospitalRouteImport } from './routes/dashboard.hospital'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyContactsRoute = EmergencyContactsRouteImport.update({
  id: '/emergency-contacts',
  path: '/emergency-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalProfileRoute = MedicalProfileRouteImport.update({
  id: '/medical-profile',
  path: '/medical-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotRoute = DashboardChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHospitalRoute = DashboardHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/first-aid': typeof FirstAidRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/register': typeof RegisterRoute
  '/sos': typeof SosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/first-aid': typeof FirstAidRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/register': typeof RegisterRoute
  '/sos': typeof SosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/first-aid': typeof FirstAidRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/register': typeof RegisterRoute
  '/sos': typeof SosRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/hospital': typeof DashboardHospitalRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/dashboard'
    | '/emergency-contacts'
    | '/first-aid'
    | '/hospitals'
    | '/login'
    | '/medical-profile'
    | '/register'
    | '/sos'
    | '/dashboard/admin'
    | '/dashboard/chatbot'
    | '/dashboard/doctor'
    | '/dashboard/driver'
    | '/dashboard/hospital'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/patient'
    | '/dashboard/profile'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/emergency-contacts'
    | '/first-aid'
    | '/hospitals'
    | '/login'
    | '/medical-profile'
    | '/register'
    | '/sos'
    | '/dashboard/admin'
    | '/dashboard/chatbot'
    | '/dashboard/doctor'
    | '/dashboard/driver'
    | '/dashboard/hospital'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/patient'
    | '/dashboard/profile'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/dashboard'
    | '/emergency-contacts'
    | '/first-aid'
    | '/hospitals'
    | '/login'
    | '/medical-profile'
    | '/register'
    | '/sos'
    | '/dashboard/admin'
    | '/dashboard/chatbot'
    | '/dashboard/doctor'
    | '/dashboard/driver'
    | '/dashboard/hospital'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/patient'
    | '/dashboard/profile'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAssistantRoute: typeof AiAssistantRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmergencyContactsRoute: typeof EmergencyContactsRoute
  FirstAidRoute: typeof FirstAidRoute
  HospitalsRoute: typeof HospitalsRoute
  LoginRoute: typeof LoginRoute
  MedicalProfileRoute: typeof MedicalProfileRoute
  RegisterRoute: typeof RegisterRoute
  SosRoute: typeof SosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-contacts': {
      id: '/emergency-contacts'
      path: '/emergency-contacts'
      fullPath: '/emergency-contacts'
      preLoaderRoute: typeof EmergencyContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-profile': {
      id: '/medical-profile'
      path: '/medical-profile'
      fullPath: '/medical-profile'
      preLoaderRoute: typeof MedicalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbot': {
      id: '/dashboard/chatbot'
      path: '/chatbot'
      fullPath: '/dashboard/chatbot'
      preLoaderRoute: typeof DashboardChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hospital': {
      id: '/dashboard/hospital'
      path: '/hospital'
      fullPath: '/dashboard/hospital'
      preLoaderRoute: typeof DashboardHospitalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardChatbotRoute: typeof DashboardChatbotRoute
  DashboardDoctorRoute: typeof DashboardDoctorRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardHospitalRoute: typeof DashboardHospitalRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardChatbotRoute: DashboardChatbotRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardHospitalRoute: DashboardHospitalRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPatientRoute: DashboardPatientRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAssistantRoute: AiAssistantRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmergencyContactsRoute: EmergencyContactsRoute,
  FirstAidRoute: FirstAidRoute,
  HospitalsRoute: HospitalsRoute,
  LoginRoute: LoginRoute,
  MedicalProfileRoute: MedicalProfileRoute,
  RegisterRoute: RegisterRoute,
  SosRoute: SosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
