import crypto from 'crypto';
import mongoose from 'mongoose';
import { ApiError } from '../utils/ApiError.js';
import { tokenService } from '../utils/token.service.js';
import { verifyFirebaseToken } from '../utils/firebaseAdmin.js';
import { sendVerificationEmail, sendPasswordResetEmail } from '../utils/sendEmail.js';
import { smsService } from '../utils/sendSMS.js';
import { auditService, AUDIT_EVENTS } from './audit.service.js';
import { VALIDATION_CONSTANTS } from '../utils/constants.js';
import { generateOTP } from '../utils/helpers.js';
import { verifyRefreshToken } from '../utils/jwt.js';

import { userRepository } from '../repositories/user.repository.js';
import { patientRepository } from '../repositories/patient.repository.js';

class AuthService {
  async registerUser(userData, metadata = {}) {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
      const existingUser = await userRepository.findOne(
        { $or: [{ email: userData.email.toLowerCase() }, { phone: userData.phone }] }, 
        session
      );
      if (existingUser) {
        throw new ApiError(409, 'User with this email or phone number already exists', 'USER_EXISTS');
      }

      const user = await userRepository.create(userData, session);
      
      if (user.role === 'patient') {
        const dob = new Date();
        dob.setFullYear(dob.getFullYear() - (userData.age || 0));
        
        await patientRepository.create({
          user: user._id,
          dateOfBirth: dob,
          bloodGroup: userData.blood || 'O+',
          gender: 'Other',
          emergencyContacts: userData.contact ? [{ name: 'Emergency Contact', phone: userData.contact, relation: 'Unknown' }] : []
        }, session);
      }

      const verificationToken = user.generateEmailVerificationToken();
      await userRepository.updateById(user._id, { 
        // Token logic generated by model method
      }, session);

      auditService.logEvent(AUDIT_EVENTS.USER_REGISTERED, user._id, { role: user.role, ip: metadata.ip });

      await session.commitTransaction();
      session.endSession();

      try {
        const verifyUrl = `http://localhost:5173/verify-email?token=${verificationToken}`;
        await sendVerificationEmail(user.email, verifyUrl);
      } catch (err) {}

      const tokens = await tokenService.createTokenPair(user, metadata);
      return { user: user.toObject(), tokens };
    } catch (error) {
      await session.abortTransaction();
      session.endSession();
      throw error;
    }
  }

  async loginUser(email, password, metadata = {}) {
    const user = await userRepository.findByEmailWithPassword(email);
    if (!user) {
      auditService.logEvent(AUDIT_EVENTS.LOGIN_FAILED, 'UNKNOWN', { reason: 'User not found', email, ip: metadata.ip });
      throw new ApiError(401, 'Invalid email or password', 'INVALID_CREDENTIALS');
    }

    if (user.isLocked) {
      auditService.logEvent(AUDIT_EVENTS.LOGIN_FAILED, user._id, { reason: 'Account locked', ip: metadata.ip });
      throw new ApiError(403, 'Account is locked. Contact support.', 'ACCOUNT_LOCKED');
    }

    const isMatch = await user.comparePassword(password);
    if (!isMatch) {
      auditService.logEvent(AUDIT_EVENTS.LOGIN_FAILED, user._id, { reason: 'Wrong password', ip: metadata.ip });
      throw new ApiError(401, 'Invalid email or password', 'INVALID_CREDENTIALS');
    }

    if (!user.isActive) {
      auditService.logEvent(AUDIT_EVENTS.LOGIN_FAILED, user._id, { reason: 'Account disabled', ip: metadata.ip });
      throw new ApiError(403, 'Account is disabled.', 'ACCOUNT_DISABLED');
    }

    auditService.logEvent(AUDIT_EVENTS.LOGIN_SUCCESS, user._id, { ip: metadata.ip });
    const tokens = await tokenService.createTokenPair(user, metadata);
    
    return { user: user.toObject(), tokens };
  }

  async refreshAccessToken(oldRefreshToken, metadata = {}) {
    let decoded;
    try {
      decoded = verifyRefreshToken(oldRefreshToken);
    } catch (error) {
      throw new ApiError(401, 'Invalid or expired refresh token');
    }

    const userId = decoded.id || decoded.sub;
    const user = await userRepository.findByIdWithStatus(userId);
    if (!user || !user.isActive) {
      throw new ApiError(401, 'User no longer exists or is inactive');
    }

    if (user.tokenVersion !== decoded.tokenVersion) {
      auditService.logEvent(AUDIT_EVENTS.REFRESH_TOKEN_REUSE_DETECTED, user._id, { reason: 'Token version mismatch', ip: metadata.ip });
      await tokenService.logoutAllUserTokens(user._id);
      throw new ApiError(401, 'Token version mismatch. Please log in again.');
    }

    return await tokenService.rotateRefreshToken(oldRefreshToken, user, metadata);
  }

  async logout(refreshToken) {
    await tokenService.logout(refreshToken);
    auditService.logEvent(AUDIT_EVENTS.LOGOUT, 'UNKNOWN');
    return true;
  }

  async logoutAllDevices(userId) {
    await tokenService.logoutAllUserTokens(userId);
    auditService.logEvent(AUDIT_EVENTS.LOGOUT_ALL, userId);
    return true;
  }

  async generatePasswordReset(email) {
    const user = await userRepository.findByEmail(email);
    if (!user) return true; // Prevent enumeration

    const resetToken = user.generatePasswordResetToken(); // generates and hashes
    await userRepository.updateById(user._id, {
      resetPasswordToken: user.resetPasswordToken,
      resetPasswordExpire: user.resetPasswordExpire
    });

    try {
      const resetUrl = `http://localhost:5173/reset-password/${resetToken}`;
      await sendPasswordResetEmail(user.email, resetUrl);
      auditService.logEvent(AUDIT_EVENTS.PASSWORD_RESET_REQUESTED, user._id);
    } catch (err) {
      await userRepository.updateById(user._id, {
        resetPasswordToken: undefined,
        resetPasswordExpire: undefined
      });
      throw new ApiError(500, 'Could not send email');
    }
    return true;
  }

  async resetPassword(token, newPassword) {
    const hashedToken = crypto.createHash('sha256').update(token).digest('hex');
    
    // Find user with valid token
    const user = await userRepository.findOne({ 
      resetPasswordToken: hashedToken, 
      resetPasswordExpire: { $gt: Date.now() } 
    });

    if (!user) {
      throw new ApiError(400, 'Invalid or expired token', 'INVALID_TOKEN');
    }

    user.password = newPassword;
    user.resetPasswordToken = undefined;
    user.resetPasswordExpire = undefined;
    user.tokenVersion += 1; // Invalidate all active sessions!
    
    await user.save(); // Model hooks will hash the new password

    await tokenService.logoutAllUserTokens(user._id);
    auditService.logEvent(AUDIT_EVENTS.PASSWORD_RESET_COMPLETED, user._id);

    return true;
  }

  async changePassword(userId, oldPassword, newPassword) {
    const user = await userRepository.findByIdWithPassword(userId);
    if (!user) throw new ApiError(404, 'User not found');

    const isMatch = await user.comparePassword(oldPassword);
    if (!isMatch) {
      throw new ApiError(401, 'Incorrect old password');
    }

    user.password = newPassword;
    user.tokenVersion += 1;
    await user.save();
    
    await tokenService.logoutAllUserTokens(user._id);
    auditService.logEvent(AUDIT_EVENTS.PASSWORD_CHANGED, user._id);
    return true;
  }

  async lockAccount(userId) {
    const user = await userRepository.updateById(userId, { isLocked: true });
    if (!user) throw new ApiError(404, 'User not found');
    await tokenService.logoutAllUserTokens(userId);
    auditService.logEvent(AUDIT_EVENTS.ACCOUNT_LOCKED, userId);
    return user;
  }

  async unlockAccount(userId) {
    const user = await userRepository.updateById(userId, { isLocked: false });
    if (!user) throw new ApiError(404, 'User not found');
    auditService.logEvent(AUDIT_EVENTS.ACCOUNT_UNLOCKED, userId);
    return user;
  }

  async changeRole(userId, newRole) {
    const user = await userRepository.updateById(userId, { role: newRole });
    if (!user) throw new ApiError(404, 'User not found');
    await tokenService.logoutAllUserTokens(userId);
    auditService.logEvent(AUDIT_EVENTS.ROLE_CHANGED, userId, { newRole });
    return user;
  }
}

export const authService = new AuthService();
