import admin from 'firebase-admin';
import { ApiError } from './ApiError.js';

/**
 * Ensures the Firebase Admin SDK is only initialized once,
 * which is important in serverless environments (like Vercel functions)
 * or when hot-reloading in development.
 */
if (!admin.apps.length) {
  try {
    // Environment variables often escape newline characters incorrectly.
    // This securely forces the correct PEM format for the private key.
    const privateKey = process.env.FIREBASE_PRIVATE_KEY
      ? process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n')
      : undefined;

    if (!process.env.FIREBASE_PROJECT_ID || !process.env.FIREBASE_CLIENT_EMAIL || !privateKey) {
      console.warn('⚠️ Firebase Admin credentials are missing from environment variables.');
    } else {
      admin.initializeApp({
        credential: admin.credential.cert({
          projectId: process.env.FIREBASE_PROJECT_ID,
          clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
          privateKey: privateKey,
        }),
      });
      console.log('🔥 Firebase Admin SDK initialized successfully');
    }
  } catch (error) {
    console.error('❌ Firebase Admin SDK initialization error:', error.stack);
  }
}

/**
 * Utility to verify a Firebase ID Token generated by the client SDK.
 * @param {string} idToken - The JWT issued by Firebase on the frontend
 * @returns {Promise<Object>} The decoded token payload (containing uid, email, etc.)
 */
export const verifyFirebaseToken = async (idToken) => {
  try {
    const decodedToken = await admin.auth().verifyIdToken(idToken);
    return decodedToken;
  } catch (error) {
    // Throw a custom ApiError to be caught by the global error handler
    throw new ApiError(401, 'Invalid or expired Firebase ID token.', 'FIREBASE_AUTH_FAILED');
  }
};

export default admin;
